##### **Colored Cubical Complexes, $C_{3,5}$** 
---

* This notebook imports $C_{3,5}$, the list of all 75 3-dimensional cubes colored with five colors.
* Given a target cube, C, and a collection of cubes, $\mathcal{C}$  (perhaps a subset of $C_{3, 5}$ or all of $C_{3, 5}$), containing eight or more distinct cubes that can contribute to a 2x2x2 build of C, we consider all subsets of 8 cubes from $\mathcal{C}$ and for each subset count the number of distinct solutions possible in a 2x2x2 build of C.


In [1]:
import csv

def csv_to_kvs(fileName):
    make_dictionary = {}
    with open(fileName,'r') as csvFile:
        csvreader = csv.reader(csvFile)
        for row in csvreader:
            #position 1 and following are integers
            make_dictionary[row[0]] = [int(val) for val in row[1:]]
        print(make_dictionary)
    return make_dictionary

C35=csv_to_kvs('C_35all.csv')  
print(C35)

print(len(C35.keys()))

keysList = list(C35.keys()) 

print(keysList)


{'112.453': [112, 113, 124, 135, 143, 152, 254, 345], '112.543': [112, 113, 125, 134, 142, 153, 245, 354], '112.354': [112, 114, 123, 134, 145, 152, 253, 354], '112.534': [112, 114, 125, 132, 143, 154, 235, 345], '112.345': [112, 115, 123, 135, 142, 154, 243, 345], '112.435': [112, 115, 124, 132, 145, 153, 234, 354], '113.524': [113, 114, 123, 135, 142, 154, 245, 253], '113.254': [113, 114, 124, 132, 145, 153, 235, 254], '113.425': [113, 115, 123, 134, 145, 152, 243, 254], '113.245': [113, 115, 125, 132, 143, 154, 234, 245], '114.325': [114, 115, 124, 135, 143, 152, 234, 253], '114.235': [114, 115, 125, 134, 142, 153, 235, 243], '221.543': [124, 145, 152, 221, 223, 234, 253, 354], '221.453': [125, 142, 154, 221, 223, 235, 243, 345], '221.354': [125, 132, 153, 221, 224, 234, 245, 354], '221.534': [123, 135, 152, 221, 224, 243, 254, 345], '221.435': [123, 134, 142, 221, 225, 245, 253, 354], '221.345': [124, 132, 143, 221, 225, 235, 254, 345], '223.514': [124, 132, 145, 153, 223, 224, 235

In [29]:
%run module2x2x2_ext_match.ipynb

from datetime import date

today = date.today()

print("Today's date:", today)

Today's date: 2022-10-13


We initially focus on the target 112.345 and look for the maximum solution number. The collection of cubes with at least 2 usable corners for the target cube 112.345. We started by looking at the collection of cubes with usable corner count greater than or equal to 4, but there were NO solutions.  


In [25]:
TestTarget=C35["112.345"]
TestCubes=keysList


def UCCsublist(ucc_output, n):
    sublist_keynames = []
    for x in ucc_output:
        if x[1] > n-1:
            sublist_keynames.append(x[0])
    return sublist_keynames
    
CubesForMaxSearch = UCCsublist(UCC(TestTarget, TestCubes, C35 ), 3)

#CubesForMaxSearch.append("112.435")

print(CubesForMaxSearch)

['112.345', '442.135', '332.415', '124.534', '123.543', '123.514', '553.214', '551.324', '551.243', '441.523', '331.254', '223.154', '221.534', '221.453', '113.524', '114.235', '113.425', '112.534', '112.453']


In [26]:
SubdictionaryFor112345Max={key: C35[key] for key in CubesForMaxSearch}   
print(len(SubdictionaryFor112345Max), SubdictionaryFor112345Max)
print(type(SubdictionaryFor112345Max))

19 {'112.345': [112, 115, 123, 135, 142, 154, 243, 345], '442.135': [123, 135, 142, 154, 243, 345, 442, 445], '332.415': [123, 135, 142, 154, 243, 332, 335, 345], '124.534': [124, 142, 145, 154, 234, 243, 345, 354], '123.543': [123, 132, 135, 153, 234, 243, 345, 354], '123.514': [123, 124, 132, 135, 142, 145, 153, 154], '553.214': [123, 135, 142, 154, 245, 253, 553, 554], '551.324': [123, 135, 152, 243, 254, 345, 551, 554], '551.243': [125, 142, 154, 235, 243, 345, 551, 553], '441.523': [125, 142, 154, 235, 243, 345, 441, 443], '331.254': [123, 135, 152, 243, 254, 331, 334, 345], '223.154': [123, 135, 142, 154, 223, 224, 245, 253], '221.534': [123, 135, 152, 221, 224, 243, 254, 345], '221.453': [125, 142, 154, 221, 223, 235, 243, 345], '113.524': [113, 114, 123, 135, 142, 154, 245, 253], '114.235': [114, 115, 125, 134, 142, 153, 235, 243], '113.425': [113, 115, 123, 134, 145, 152, 243, 254], '112.534': [112, 114, 125, 132, 143, 154, 235, 345], '112.453': [112, 113, 124, 135, 143, 152, 

The SolutionFrequencyList function first calculates (and displays) the number of subsets of 8 cubes from the input subdictionary collection. Then for each subset of eight cubes, it counts the number of ways those eight cubes can be used to create a 2x2x2 version of the target cube. This 'number of ways' is the solution number for the target and the eight cubes. When this is count is complete for every collection of eight cubes, then the distribution of solution numbers is created 
'solution number':'number of collections of eight cubes that have that solution number'.

In [30]:
SolutionFrequencyList(SubdictionaryFor112345Max, C35["112.345"])  

There are 75582 collections to make the target [112, 115, 123, 135, 142, 154, 243, 345]
.
.
.
.
.
.
.
Checked 75582 collections of 8 cubes
26169 of the collections yield no solutions
 400 :  256
 392 :  4
 376 :  96
 372 :  96
 368 :  96
 360 :  64
 356 :  96
 352 :  96
 348 :  88
 336 :  96
 332 :  72
 292 :  24
 280 :  12
 272 :  1152
 264 :  936
 256 :  696
 252 :  64
 248 :  1136
 244 :  192
 228 :  48
 224 :  192
 216 :  576
 208 :  6
 204 :  224
 200 :  192
 192 :  556
 188 :  576
 184 :  968
 176 :  448
 168 :  800
 164 :  544
 160 :  2688
 156 :  1392
 152 :  864
 148 :  144
 144 :  312
 140 :  336
 136 :  384
 132 :  12
 128 :  128
 120 :  920
 112 :  8064
 108 :  32
 104 :  3264
 100 :  96
 96 :  6513
 84 :  56
 80 :  1992
 76 :  1728
 72 :  7372
 60 :  1360
 48 :  1228
 24 :  126


In [ ]:
CollectionsToMakeTarget(SubdictionaryFor112345Max, C35["112.345"])

In [10]:
CornerCountVector([[112, 115, 123, 135, 142, 154, 243, 345],
  [123, 135, 142, 154, 243, 345, 442, 445],
  [123, 135, 142, 154, 243, 332, 335, 345],
  [124, 142, 145, 154, 234, 243, 345, 354],
  [123, 132, 135, 153, 234, 243, 345, 354],
  [123, 124, 132, 135, 142, 145, 153, 154],
  [123, 135, 142, 154, 245, 253, 553, 554],
  [123, 135, 152, 243, 254, 345, 551, 554]], [112, 115, 123, 135, 142, 154, 243, 345])

[[112, 1, [2]],
 [115, 1, [2]],
 [123, 7, [2, 3, 5, 11, 13, 17, 19]],
 [135, 7, [2, 3, 5, 11, 13, 17, 19]],
 [142, 6, [2, 3, 5, 7, 13, 17]],
 [154, 6, [2, 3, 5, 7, 13, 17]],
 [243, 6, [2, 3, 5, 7, 11, 19]],
 [345, 6, [2, 3, 5, 7, 11, 19]]]

Wow, I originallly thougth there was an issue, but no problem with code above. In all the cubes with usable corner count ($ucc$)  greater than or equal to 4, there is only one cube with both corners 112 and 115 and that cube is the target cube. We must go down to include $ucc \geq 3$ when looking for non-zero solution numbers.

In [8]:
CubesForMaxSearch = UCCsublist(UCC(TestTarget, TestCubes, C35 ), 3)

CubesForMaxSearch.append("112.435")

print(CubesForMaxSearch)

['112.345', '442.135', '332.415', '124.534', '123.543', '123.514', '553.214', '551.324', '551.243', '441.523', '331.254', '223.154', '221.534', '221.453', '113.524', '114.235', '113.425', '112.534', '112.453', '112.435']


In [10]:
SubdictionaryFor112345Max={key: C35[key] for key in CubesForMaxSearch}   
print(len(SubdictionaryFor112345Max), SubdictionaryFor112345Max)
print(type(SubdictionaryFor112345Max))

SolutionFrequencyList(SubdictionaryFor112345Max, C35["112.345"])  

20 {'112.345': [112, 115, 123, 135, 142, 154, 243, 345], '442.135': [123, 135, 142, 154, 243, 345, 442, 445], '332.415': [123, 135, 142, 154, 243, 332, 335, 345], '124.534': [124, 142, 145, 154, 234, 243, 345, 354], '123.543': [123, 132, 135, 153, 234, 243, 345, 354], '123.514': [123, 124, 132, 135, 142, 145, 153, 154], '553.214': [123, 135, 142, 154, 245, 253, 553, 554], '551.324': [123, 135, 152, 243, 254, 345, 551, 554], '551.243': [125, 142, 154, 235, 243, 345, 551, 553], '441.523': [125, 142, 154, 235, 243, 345, 441, 443], '331.254': [123, 135, 152, 243, 254, 331, 334, 345], '223.154': [123, 135, 142, 154, 223, 224, 245, 253], '221.534': [123, 135, 152, 221, 224, 243, 254, 345], '221.453': [125, 142, 154, 221, 223, 235, 243, 345], '113.524': [113, 114, 123, 135, 142, 154, 245, 253], '114.235': [114, 115, 125, 134, 142, 153, 235, 243], '113.425': [113, 115, 123, 134, 145, 152, 243, 254], '112.534': [112, 114, 125, 132, 143, 154, 235, 345], '112.453': [112, 113, 124, 135, 143, 152, 

In [20]:
MyCubes=['221.534', '221.453', '113.524', '114.235', '113.425', '112.534', '112.453', '112.345', '442.135']
Subdictionary={key: C35[key] for key in MyCubes} 
print(Subdictionary)

SomeCollections=CollectionsToMakeTarget(Subdictionary, C35['112.345'])
#CornerCountVector(Subdictionary, C35['112.345'])

{'221.534': [123, 135, 152, 221, 224, 243, 254, 345], '221.453': [125, 142, 154, 221, 223, 235, 243, 345], '113.524': [113, 114, 123, 135, 142, 154, 245, 253], '114.235': [114, 115, 125, 134, 142, 153, 235, 243], '113.425': [113, 115, 123, 134, 145, 152, 243, 254], '112.534': [112, 114, 125, 132, 143, 154, 235, 345], '112.453': [112, 113, 124, 135, 143, 152, 254, 345], '112.345': [112, 115, 123, 135, 142, 154, 243, 345], '442.135': [123, 135, 142, 154, 243, 345, 442, 445]}
There are 9 collections to make the target [112, 115, 123, 135, 142, 154, 243, 345]


In [21]:
print(C35['112.345'])

[112, 115, 123, 135, 142, 154, 243, 345]


In [22]:
CornerCountVector(SomeCollections, C35['112.345'])

[[112, 0, []],
 [115, 0, []],
 [123, 0, []],
 [135, 0, []],
 [142, 0, []],
 [154, 0, []],
 [243, 0, []],
 [345, 0, []]]